name: Ubuntu Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test-ubuntu:
    name: Test Project on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #! Update for your project's python version!
        python-version:
          - "3.8"
          # - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: pytest -v Tests/

  test-39-with-coverage:
    # Use a specific python version (excluded in the tests above) to run coverage tests.
    name: Test Python 3.9 and Upload Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        #! Update project name
        run: pytest --capture=sys -v --cov=CythonProjectTemplate ..\Tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          flags: unittests
          verbose: true
          name: coverage
